# Generated by Django 4.0.4 on 2022-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students_about_me_students_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
