# Generated by Django 4.0.4 on 2022-05-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='Yapılacaklar',
        ),
    ]
