# Generated by Django 4.0.4 on 2022-05-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
