# Generated by Django 4.0.4 on 2022-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0004_student_last_update_date_student_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
