# Generated by Django 4.0.4 on 2022-05-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['number'], 'verbose_name_plural': 'Öğrenciler'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student_Table',
        ),
    ]
